apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb8
  strategy: {}
  template:
    metadata:
      labels:
        app: mysqldb8
    spec:
      containers:
      - image: mysql:8
        name: mysqldb8
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: secret
          - name: MYSQL_DATABASE
            value: ms_usuarios

